name: clean_architecture_trivia_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.5
  # Service Locator
  get_it: ^7.2.0
  # Local cache
  shared_preferences: ^2.0.15
  #  Value Equality
  equatable: ^2.0.5
  #  Functional Programming Thingies
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
